import Anthropic from "@anthropic-ai/sdk";
import { env } from "@/lib/env";
import { toImageBlock } from "@/lib/imageBlock";
import {
  type DirectorOutput,
  type Motion,
  type Shot,
  type SourceImage,
} from "@/lib/types";

/**
 * Director step: Claude (claude-sonnet-5, vision) plans the walk-through.
 *
 * One shot per ROOM (not per photo): the images are grouped by their
 * user-confirmed labels, and Claude plans a single clip per room, grounded in
 * every photo of that room, picking the photo that makes the best start frame.
 * It returns shots by *image index* (not URL) so it never has to echo multi-MB
 * data URLs back; we map index → original URL locally. Output is constrained by
 * a JSON schema and re-validated on our side, with one retry if the model
 * somehow returns something unusable.
 */

const MODEL = "claude-sonnet-5";

const SYSTEM = `You are the director of a short, cinematic real-estate video tour.
You will be shown a set of property photos, each labelled "Image <n>". Every clip
is produced by an image-to-video model that animates ONE photo with a moving
camera and CANNOT see any of the other photos, so YOU must give it, in words, all
the spatial context and detail it needs. Work in two stages and return JSON only.

LABELS ARE GROUND TRUTH. Photos may carry a label, e.g. Image 3 (labelled
"Bedroom two"). Labels are the user's confirmed room assignments, made after
personally reviewing and correcting every photo, and they OVERRIDE anything you
infer from the pixels:
- Use a labelled photo's label VERBATIM as that shot's "room". Never rename,
  re-sort or merge labelled photos into a different room.
- Photos sharing a label are the same physical space; photos with different
  labels are different spaces, even if they look similar.
- Use the same label names when referring to rooms in "openPlanWith",
  "layout" and every "shotPrompt".

STAGE 1: Understand the whole property from ALL photos together.
- Decide which photos show the SAME physical space from different angles (match the
  furniture, floor, lighting, windows, art). Give one space one consistent room
  name — the user's label when present.
- Build a single floor-plan in your head: how the spaces connect, which areas are
  open-plan (flow together with no dividing wall), and where each thing, kitchen,
  dining table, sofa, TV, stairs, doors, windows, actually sits relative to the
  others. Many homes are one big open-plan living/dining/kitchen: treat it as one
  connected space and know exactly where each part is.
- Summarise the real layout in "layout" (2-4 sentences).

STAGE 2: Plan ONE CONTINUOUS WALKTHROUGH.
The final video is a single, uninterrupted first-person walk through the whole
property, as if filmed by a real-estate videographer on a stabilized gimbal.
It is assembled from consecutive SEGMENTS: each segment is generated by a video
model from exactly two photos — a start frame and an end frame — and the camera
must travel naturally from the exact start viewpoint to the exact end viewpoint.
Consecutive segments share their boundary photo, so the finished film has no
cuts and no teleporting.

- "path": the ordered waypoints of the walk. Visit every room from the list
  EXACTLY once, in the most natural physical order: exterior/entrance first if
  present, then the connected living spaces, then private rooms (bedrooms,
  bathrooms), ending on the most memorable space (e.g. a view or garden) when
  there is one. Keep open-plan-connected rooms adjacent. For each room pick the
  ONE photo that best serves as the standing viewpoint in that room (the
  widest, clearest, most representative view). Use the room names verbatim.
- "segments": one entry per consecutive pair of waypoints, in order (a path of
  N rooms has exactly N-1 segments).
  * "walkPrompt": the most important field — a complete, self-contained prompt
    for segment i, describing the walk from path[i] to path[i+1]. The video
    model sees ONLY the two endpoint photos plus this text. Describe the
    continuous camera move: which way the camera turns, what doorway, hallway
    or opening it passes through, and what is genuinely visible along the way
    based on the photos and your STAGE 1 layout. Respect open-plan connections:
    connected spaces flow into each other with no wall. ACCURACY FIRST:
    preserve the exact architecture, furniture placement, decor, colours,
    materials and lighting of both endpoint photos; never restyle, add or
    remove anything.
  * NO PHOTO = NO CONTEXT. If the connection between the two rooms is not
    visible in any photo, keep the transition minimal and neutral — a short,
    smooth move through a plain doorway or hallway that continues the walls
    and flooring already visible — and say so explicitly. Never invent
    furniture, windows, art or extra rooms along the way.
  * "caption": ≤6 words for the segment, evocative, sentence case, no end
    punctuation.
- "title": a concise, editorial name for the whole tour.`;

/** JSON schema Claude must satisfy (structured outputs). */
const SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    title: { type: "string" },
    layout: { type: "string" },
    path: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          room: { type: "string" },
          imageIndex: { type: "integer" },
        },
        required: ["room", "imageIndex"],
      },
    },
    segments: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          walkPrompt: { type: "string" },
          caption: { type: "string" },
        },
        required: ["walkPrompt", "caption"],
      },
    },
  },
  required: ["title", "layout", "path", "segments"],
} as const;

interface RawWaypoint {
  room?: unknown;
  imageIndex?: unknown;
}
interface RawSegment {
  walkPrompt?: unknown;
  caption?: unknown;
}

/** One user-confirmed room and the indexes of its photos. */
interface RoomGroupIn {
  room: string;
  imageIndexes: number[];
}

/**
 * Group the images into rooms by their user-confirmed labels, preserving the
 * board order. Unlabeled images (shouldn't happen via the UI) each become their
 * own room so nothing is silently dropped.
 */
function groupByLabel(images: SourceImage[]): RoomGroupIn[] {
  const order: string[] = [];
  const byKey = new Map<string, RoomGroupIn>();
  images.forEach((img, i) => {
    const label = img.label?.trim();
    const key = label ? label.toLowerCase() : `__solo_${i}`;
    let group = byKey.get(key);
    if (!group) {
      group = { room: label || `Room ${byKey.size + 1}`, imageIndexes: [] };
      byKey.set(key, group);
      order.push(key);
    }
    group.imageIndexes.push(i);
  });
  return order.map((k) => byKey.get(k)!);
}
interface RawPlan {
  title: string;
  layout?: string;
  path: RawWaypoint[];
  segments: RawSegment[];
}

const trimCaption = (c: string) => c.trim().split(/\s+/).slice(0, 6).join(" ");

/** Placeholder motion for walkthrough legs (the walk is prompt-driven). */
const DEFAULT_MOTION: Motion = "Push In";

/**
 * Validate + normalize the model output into DirectorOutput, or return null.
 *
 * Guarantees enforced here regardless of what the model returns:
 *  - The path visits every user-confirmed room exactly once (duplicates are
 *    dropped, forgotten rooms are appended at the end).
 *  - Each waypoint's photo belongs to its own room, else its first photo.
 *  - A path of N rooms yields exactly N-1 walkthrough legs; a single-room tour
 *    falls back to one classic single-frame clip.
 */
function coerce(
  plan: RawPlan,
  images: SourceImage[],
  groups: RoomGroupIn[],
): DirectorOutput | null {
  if (!plan || typeof plan.title !== "string" || !Array.isArray(plan.path)) {
    return null;
  }
  const groupByRoom = new Map(
    groups.map((g) => [g.room.trim().toLowerCase(), g]),
  );

  // Resolve the ordered waypoints: one per room, model's order, our rooms.
  const waypoints: { room: string; imageIndex: number }[] = [];
  const seen = new Set<string>();
  for (const w of plan.path) {
    const key = String(w?.room ?? "")
      .trim()
      .toLowerCase();
    const group = groupByRoom.get(key);
    if (!group || seen.has(key)) continue; // unknown room or duplicate: drop
    seen.add(key);
    const pick = Number(w?.imageIndex);
    waypoints.push({
      room: group.room,
      imageIndex: group.imageIndexes.includes(pick)
        ? pick
        : group.imageIndexes[0],
    });
  }
  for (const g of groups) {
    const key = g.room.trim().toLowerCase();
    if (seen.has(key)) continue;
    console.warn(
      `[director] room "${g.room}" missing from the path: appending it`,
    );
    waypoints.push({ room: g.room, imageIndex: g.imageIndexes[0] });
  }
  if (waypoints.length === 0) return null;

  // Single room: no walk to make — one classic clip of that space.
  if (waypoints.length === 1) {
    const seg = Array.isArray(plan.segments) ? plan.segments[0] : undefined;
    const prompt =
      typeof seg?.walkPrompt === "string" && seg.walkPrompt.trim()
        ? seg.walkPrompt.trim()
        : undefined;
    return {
      title: plan.title.trim() || "Property tour",
      shots: [
        {
          imageUrl: images[waypoints[0].imageIndex].url,
          room: waypoints[0].room,
          openPlanWith: [],
          shotPrompt: prompt,
          motion: DEFAULT_MOTION,
          caption: trimCaption(String(seg?.caption ?? "")),
        },
      ],
    };
  }

  // Walkthrough legs: consecutive waypoint pairs sharing boundary photos.
  const segments = Array.isArray(plan.segments) ? plan.segments : [];
  const shots: Shot[] = [];
  for (let i = 0; i < waypoints.length - 1; i++) {
    const from = waypoints[i];
    const to = waypoints[i + 1];
    const seg = segments[i];
    const walkPrompt =
      typeof seg?.walkPrompt === "string" && seg.walkPrompt.trim()
        ? seg.walkPrompt.trim()
        : undefined;
    shots.push({
      imageUrl: images[from.imageIndex].url,
      endImageUrl: images[to.imageIndex].url,
      imageUrls: [images[from.imageIndex].url, images[to.imageIndex].url],
      room: `${from.room} → ${to.room}`,
      openPlanWith: [],
      shotPrompt: walkPrompt,
      motion: DEFAULT_MOTION,
      caption: trimCaption(String(seg?.caption ?? "")),
    });
  }

  return { title: plan.title.trim() || "Property tour", shots };
}

async function callClaude(
  client: Anthropic,
  images: SourceImage[],
  groups: RoomGroupIn[],
  meta?: { title?: string },
): Promise<RawPlan> {
  const content: Anthropic.ContentBlockParam[] = [];
  for (let i = 0; i < images.length; i++) {
    const img = images[i];
    content.push({
      type: "text",
      text: `Image ${i}${img.label ? ` (labelled "${img.label}")` : ""}:`,
    });
    content.push(await toImageBlock(img));
  }
  const roomList = groups
    .map((g) => `- "${g.room}": images ${g.imageIndexes.join(", ")}`)
    .join("\n");
  content.push({
    type: "text",
    text:
      `Here are ${images.length} photos of one property` +
      (meta?.title ? ` titled "${meta.title}".` : ".") +
      `\n\nThe user confirmed these ${groups.length} rooms:\n${roomList}\n\n` +
      `Plan one continuous walkthrough visiting all ${groups.length} rooms ` +
      `(a path of ${groups.length} waypoints and ${Math.max(1, groups.length - 1)} segments) ` +
      "and return it as JSON matching the schema.",
  });

  const res = await client.messages.create({
    model: MODEL,
    // Each shot now carries a full, self-contained shotPrompt plus a global
    // layout, so give the model ample room for up to MAX_IMAGES detailed shots.
    max_tokens: 8000,
    thinking: { type: "disabled" },
    system: SYSTEM,
    output_config: { format: { type: "json_schema", schema: SCHEMA } },
    messages: [{ role: "user", content }],
  });

  const text = res.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("");
  return JSON.parse(text) as RawPlan;
}

export async function director(
  images: SourceImage[],
  meta?: { title?: string },
): Promise<DirectorOutput> {
  if (images.length === 0) throw new Error("No images to direct.");
  const client = new Anthropic({ apiKey: env.anthropicKey() });
  const groups = groupByLabel(images);

  // Attempt, then retry once if the result is malformed/unusable.
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      console.log(
        `[director] calling ${MODEL} (attempt ${attempt + 1}, ` +
          `${images.length} images → ${groups.length} rooms)…`,
      );
      const raw = await callClaude(client, images, groups, meta);
      const plan = coerce(raw, images, groups);
      if (plan) {
        if (typeof raw.layout === "string" && raw.layout.trim()) {
          console.log(`[director] layout: ${raw.layout.trim()}`);
        }
        console.log(
          `[director] ok: "${plan.title}", ${plan.shots.length} shots ` +
            `(${images.length} images in)`,
        );
        return plan;
      }
      console.warn(`[director] attempt ${attempt + 1} returned an invalid plan`);
    } catch (err) {
      console.warn(`[director] attempt ${attempt + 1} error:`, err);
      if (attempt === 1) {
        const msg = err instanceof Error ? err.message : "unknown error";
        throw new Error(`Director failed: ${msg}`);
      }
    }
  }
  throw new Error("Director returned an invalid plan after a retry.");
}
